networks:
  ormuz:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/24

services:

  # ─── Ledger ─────────────────────────────────────────────────────────────────

  ledger-norte:
    build:
      context: .
      args:
        TARGET: ledger
    container_name: ledger_norte
    networks:
      ormuz:
        ipv4_address: 10.200.0.7
    restart: unless-stopped
    ports:
      - "7007:7000"
    environment:
      - NODE_ID=ledger-norte
      - PORT=7000
      - GENESIS=true
      - DIFFICULTY=3
      - PEERS=10.200.0.8:7000,10.200.0.10:7000,10.200.0.16:7000

  ledger-sul:
    build:
      context: .
      args:
        TARGET: ledger
    container_name: ledger_sul
    networks:
      ormuz:
        ipv4_address: 10.200.0.8
    restart: unless-stopped
    ports:
      - "7008:7000"
    environment:
      - NODE_ID=ledger-sul
      - PORT=7000
      - GENESIS=false
      - DIFFICULTY=3
      - PEERS=10.200.0.7:7000,10.200.0.10:7000,10.200.0.16:7000

  ledger-leste:
    build:
      context: .
      args:
        TARGET: ledger
    container_name: ledger_leste
    networks:
      ormuz:
        ipv4_address: 10.200.0.10
    restart: unless-stopped
    ports:
      - "7010:7000"
    environment:
      - NODE_ID=ledger-leste
      - PORT=7000
      - GENESIS=false
      - DIFFICULTY=3
      - PEERS=10.200.0.7:7000,10.200.0.8:7000,10.200.0.16:7000

  ledger-oeste:
    build:
      context: .
      args:
        TARGET: ledger
    container_name: ledger_oeste
    networks:
      ormuz:
        ipv4_address: 10.200.0.16
    restart: unless-stopped
    ports:
      - "7016:7000"
    environment:
      - NODE_ID=ledger-oeste
      - PORT=7000
      - GENESIS=false
      - DIFFICULTY=3
      - PEERS=10.200.0.7:7000,10.200.0.8:7000,10.200.0.10:7000

  # ─── Brokers ─────────────────────────────────────────────────────────────────

  broker-norte:
    build:
      context: .
      args:
        TARGET: broker
    container_name: broker_norte
    networks:
      ormuz:
        ipv4_address: 10.200.0.17
    restart: unless-stopped
    ports:
      - "5007:5000"
    environment:
      - SECTOR_NAME=Norte
      - PORT=5000
      - MY_IP=10.200.0.17
      - RING_ADDRS=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000
      - LEDGER_NODES=10.200.0.7:7000,10.200.0.8:7000,10.200.0.10:7000,10.200.0.16:7000

  broker-sul:
    build:
      context: .
      args:
        TARGET: broker
    container_name: broker_sul
    networks:
      ormuz:
        ipv4_address: 10.200.0.18
    restart: unless-stopped
    ports:
      - "5008:5000"
    environment:
      - SECTOR_NAME=Sul
      - PORT=5000
      - MY_IP=10.200.0.18
      - RING_ADDRS=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000
      - LEDGER_NODES=10.200.0.7:7000,10.200.0.8:7000,10.200.0.10:7000,10.200.0.16:7000

  broker-leste:
    build:
      context: .
      args:
        TARGET: broker
    container_name: broker_leste
    networks:
      ormuz:
        ipv4_address: 10.200.0.20
    restart: unless-stopped
    ports:
      - "5010:5000"
    environment:
      - SECTOR_NAME=Leste
      - PORT=5000
      - MY_IP=10.200.0.20
      - RING_ADDRS=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000
      - LEDGER_NODES=10.200.0.7:7000,10.200.0.8:7000,10.200.0.10:7000,10.200.0.16:7000

  broker-oeste:
    build:
      context: .
      args:
        TARGET: broker
    container_name: broker_oeste
    networks:
      ormuz:
        ipv4_address: 10.200.0.26
    restart: unless-stopped
    ports:
      - "5016:5000"
    environment:
      - SECTOR_NAME=Oeste
      - PORT=5000
      - MY_IP=10.200.0.26
      - RING_ADDRS=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000
      - LEDGER_NODES=10.200.0.7:7000,10.200.0.8:7000,10.200.0.10:7000,10.200.0.16:7000

  # ─── Sensores ────────────────────────────────────────────────────────────────

  sensor-norte-radar:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor_norte_radar
    networks:
      - ormuz
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Norte
      - SENSOR_TYPE=Radar
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  sensor-norte-naval:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor_norte_naval
    networks:
      - ormuz
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Norte
      - SENSOR_TYPE=Naval
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  sensor-sul-radar:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor_sul_radar
    networks:
      - ormuz
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Sul
      - SENSOR_TYPE=Radar
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  sensor-sul-naval:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor_sul_naval
    networks:
      - ormuz
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Sul
      - SENSOR_TYPE=Naval
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  sensor-leste-radar:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor_leste_radar
    networks:
      - ormuz
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Leste
      - SENSOR_TYPE=Radar
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  sensor-leste-naval:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor_leste_naval
    networks:
      - ormuz
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Leste
      - SENSOR_TYPE=Naval
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  sensor-oeste-radar:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor_oeste_radar
    networks:
      - ormuz
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Oeste
      - SENSOR_TYPE=Radar
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  sensor-oeste-naval:
    build:
      context: .
      args:
        TARGET: sensor
    container_name: sensor_oeste_naval
    networks:
      - ormuz
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Oeste
      - SENSOR_TYPE=Naval
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  # ─── Drones ──────────────────────────────────────────────────────────────────

  drone-norte-01:
    build:
      context: .
      args:
        TARGET: drone
    container_name: drone_norte_01
    networks:
      ormuz:
        ipv4_address: 10.200.0.31
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Norte
      - DRONE_ID=DRONE-NORTE-A
      - DRONE_PORT=6000
      - MY_IP=10.200.0.31
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  drone-norte-02:
    build:
      context: .
      args:
        TARGET: drone
    container_name: drone_norte_02
    networks:
      ormuz:
        ipv4_address: 10.200.0.32
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Norte
      - DRONE_ID=DRONE-NORTE-B
      - DRONE_PORT=6000
      - MY_IP=10.200.0.32
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  drone-sul-01:
    build:
      context: .
      args:
        TARGET: drone
    container_name: drone_sul_01
    networks:
      ormuz:
        ipv4_address: 10.200.0.33
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Sul
      - DRONE_ID=DRONE-SUL-A
      - DRONE_PORT=6000
      - MY_IP=10.200.0.33
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  drone-sul-02:
    build:
      context: .
      args:
        TARGET: drone
    container_name: drone_sul_02
    networks:
      ormuz:
        ipv4_address: 10.200.0.34
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Sul
      - DRONE_ID=DRONE-SUL-B
      - DRONE_PORT=6000
      - MY_IP=10.200.0.34
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  drone-leste-01:
    build:
      context: .
      args:
        TARGET: drone
    container_name: drone_leste_01
    networks:
      ormuz:
        ipv4_address: 10.200.0.35
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Leste
      - DRONE_ID=DRONE-LESTE-A
      - DRONE_PORT=6000
      - MY_IP=10.200.0.35
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  drone-leste-02:
    build:
      context: .
      args:
        TARGET: drone
    container_name: drone_leste_02
    networks:
      ormuz:
        ipv4_address: 10.200.0.36
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Leste
      - DRONE_ID=DRONE-LESTE-B
      - DRONE_PORT=6000
      - MY_IP=10.200.0.36
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  drone-oeste-01:
    build:
      context: .
      args:
        TARGET: drone
    container_name: drone_oeste_01
    networks:
      ormuz:
        ipv4_address: 10.200.0.37
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Oeste
      - DRONE_ID=DRONE-OESTE-A
      - DRONE_PORT=6000
      - MY_IP=10.200.0.37
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  drone-oeste-02:
    build:
      context: .
      args:
        TARGET: drone
    container_name: drone_oeste_02
    networks:
      ormuz:
        ipv4_address: 10.200.0.38
    restart: unless-stopped
    environment:
      - SECTOR_NAME=Oeste
      - DRONE_ID=DRONE-OESTE-B
      - DRONE_PORT=6000
      - MY_IP=10.200.0.38
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000

  # ─── Cliente Interativo ───────────────────────────────────────────────────

  client:
    build:
      context: .
      args:
        TARGET: client
    container_name: ormuz_client
    networks:
      - ormuz
    stdin_open: true  # mantém stdin aberto para o menu interativo
    tty: true         # aloca pseudo-TTY para formatação correta do terminal
    environment:
      #   NavegacaoNorte | NavegacaoSul | NavegacaoLeste | NavegacaoOeste | ConsorcioGeral
      - COMPANY=NavegacaoNorte
      - LEDGER_NODES=10.200.0.7:7000,10.200.0.8:7000,10.200.0.10:7000,10.200.0.16:7000
      - BROKER_LIST=10.200.0.17:5000,10.200.0.18:5000,10.200.0.20:5000,10.200.0.26:5000